astra_db:
  collection_name: "ecommercedata"

embedding_model:
  google:
    provider: "google"
    model_name: "gemini-embedding-001"
  openai:
    provider: "openai"
    model_name: "text-embedding-3-small"


retriever:
  top_k: 10

llm:
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
    temperature: 0.0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.5-flash"

  openai:
    provider: "openai"
    model_name: "gpt-4o"
    temperature: 0.0
    max_output_tokens: 2048

